# Generated by Django 4.2.5 on 2023-10-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "texto",
                    models.CharField(help_text="Digite o comentario", max_length=100),
                ),
                (
                    "idPublicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.publicacao",
                    ),
                ),
            ],
        ),
    ]
